### ISSUE TITLE
Error when parse tokens, and file .exe somehow detect virus

### ISSUE THREAD

**Issue by Ikhari** [GuFFy12/Discord-Token-Checker#6]
>Check validity tokens? [Y/N]: y

>Check nitro and payments on tokens? [Y/N]: y

Parse tokens...
Traceback (most recent call last):
  File "d:\Project Random by Ikhari\Python\TokenChecker.py", line 284, in <module>
    main()
  File "d:\Project Random by Ikhari\Python\TokenChecker.py", line 135, in main
    for line in [x.strip() for x in open(f"{tokenFileName}", errors="ignore").readlines() if x.strip()]:
UnboundLocalError: local variable 'tokenFileName' referenced before assignment

**Comment by matoqueimado** [comment]
> 

fix pls

**Comment by GuFFy12** [comment]
> > 
> 
> fix pls

New update
